import MyLibrary as ml
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.setFixedSize(QtCore.QSize(777, 565))
		MainWindow.setWindowIcon(QIcon('Images/Main.png'))
		MainWindow.setStyleSheet("background-color: rgb(3, 15, 42);color: #ecf0f1")
		MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
		MainWindow.setDocumentMode(False)
		MainWindow.setDockNestingEnabled(False)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.input_label = QtWidgets.QLabel(self.centralwidget)
		self.input_label.setGeometry(QtCore.QRect(40, 130, 81, 21))
		font = QtGui.QFont()
		font.setFamily("Times New Roman")
		font.setPointSize(14)
		font.setBold(False)
		font.setWeight(50)
		self.input_label.setFont(font)
		self.input_label.setStyleSheet("color:rgb(235, 235, 0);")
		self.input_label.setObjectName("input_label")
		self.fast_insight_label = QtWidgets.QLabel(self.centralwidget)
		self.fast_insight_label.setGeometry(QtCore.QRect(30, 20, 180, 45))
		font = QtGui.QFont()
		font.setPointSize(18)
		font.setBold(False)
		font.setWeight(50)
		self.fast_insight_label.setFont(font)
		self.fast_insight_label.setStyleSheet("color: rgb(35, 71, 188);")
		self.fast_insight_label.setFrameShape(QtWidgets.QFrame.Box)
		self.fast_insight_label.setFrameShadow(QtWidgets.QFrame.Plain)
		self.fast_insight_label.setLineWidth(2)
		self.fast_insight_label.setAlignment(QtCore.Qt.AlignCenter)
		self.fast_insight_label.setWordWrap(False)
		self.fast_insight_label.setObjectName("fast_insight_label")
		self.input_lineedit = QtWidgets.QLineEdit(self.centralwidget)
		self.input_lineedit.setGeometry(QtCore.QRect(130, 130, 221, 21))
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setItalic(False)
		font.setUnderline(False)
		font.setStrikeOut(False)
		font.setKerning(True)
		font.setStyleStrategy(QtGui.QFont.PreferDefault)
		self.input_lineedit.setFont(font)
		self.input_lineedit.setStyleSheet("background-color: rgb(35, 71, 188);\n"
		"color: rgb(168, 168, 168);")
		self.input_lineedit.setFrame(False)
		self.input_lineedit.setObjectName("input_lineedit")
		self.average_label = QtWidgets.QLabel(self.centralwidget)
		self.average_label.setGeometry(QtCore.QRect(40, 190, 81, 21))
		font = QtGui.QFont()
		font.setFamily("Times New Roman")
		font.setPointSize(14)
		font.setBold(False)
		font.setWeight(50)
		self.average_label.setFont(font)
		self.average_label.setStyleSheet("color:rgb(235, 235, 0);")
		self.average_label.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.average_label.setFrameShadow(QtWidgets.QFrame.Raised)
		self.average_label.setObjectName("average_label")
		self.average_lineedit = QtWidgets.QLineEdit(self.centralwidget)
		self.average_lineedit.setGeometry(QtCore.QRect(130, 190, 221, 21))
		self.average_lineedit.setAcceptDrops(True)
		self.average_lineedit.setStyleSheet("background-color: rgb(35, 71, 188); color: rgb(235, 235, 235)")
		self.average_lineedit.setInputMethodHints(QtCore.Qt.ImhNone)
		self.average_lineedit.setText("")
		self.average_lineedit.setFrame(False)
		self.average_lineedit.setDragEnabled(False)
		self.average_lineedit.setReadOnly(True)
		self.average_lineedit.setObjectName("average_lineedit")
		self.median_label = QtWidgets.QLabel(self.centralwidget)
		self.median_label.setGeometry(QtCore.QRect(40, 250, 81, 21))
		font = QtGui.QFont()
		font.setFamily("Times New Roman")
		font.setPointSize(14)
		font.setBold(False)
		font.setWeight(50)
		self.median_label.setFont(font)
		self.median_label.setStyleSheet("color:rgb(235, 235, 0);")
		self.median_label.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.median_label.setFrameShadow(QtWidgets.QFrame.Raised)
		self.median_label.setObjectName("median_label")
		self.mode_label = QtWidgets.QLabel(self.centralwidget)
		self.mode_label.setGeometry(QtCore.QRect(40, 310, 81, 21))
		font = QtGui.QFont()
		font.setFamily("Times New Roman")
		font.setPointSize(14)
		font.setBold(False)
		font.setWeight(50)
		self.mode_label.setFont(font)
		self.mode_label.setStyleSheet("color:rgb(235, 235, 0);")
		self.mode_label.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.mode_label.setFrameShadow(QtWidgets.QFrame.Raised)
		self.mode_label.setObjectName("mode_label")
		self.cv_label = QtWidgets.QLabel(self.centralwidget)
		self.cv_label.setGeometry(QtCore.QRect(40, 490, 221, 21))
		font = QtGui.QFont()
		font.setFamily("Times New Roman")
		font.setPointSize(14)
		font.setBold(False)
		font.setWeight(50)
		self.cv_label.setFont(font)
		self.cv_label.setStyleSheet("color:rgb(235, 235, 0);")
		self.cv_label.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.cv_label.setFrameShadow(QtWidgets.QFrame.Raised)
		self.cv_label.setObjectName("cv_label")
		self.standard_deviation_label = QtWidgets.QLabel(self.centralwidget)
		self.standard_deviation_label.setGeometry(QtCore.QRect(40, 430, 200, 21))
		font = QtGui.QFont()
		font.setFamily("Times New Roman")
		font.setPointSize(14)
		font.setBold(False)
		font.setWeight(50)
		self.standard_deviation_label.setFont(font)
		self.standard_deviation_label.setStyleSheet("color:rgb(235, 235, 0);")
		self.standard_deviation_label.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.standard_deviation_label.setFrameShadow(QtWidgets.QFrame.Raised)
		self.standard_deviation_label.setObjectName("standard_deviation_label")
		self.variance_label = QtWidgets.QLabel(self.centralwidget)
		self.variance_label.setGeometry(QtCore.QRect(40, 370, 81, 21))
		font = QtGui.QFont()
		font.setFamily("Times New Roman")
		font.setPointSize(14)
		font.setBold(False)
		font.setWeight(50)
		self.variance_label.setFont(font)
		self.variance_label.setStyleSheet("color:rgb(235, 235, 0);")
		self.variance_label.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.variance_label.setFrameShadow(QtWidgets.QFrame.Raised)
		self.variance_label.setObjectName("variance_label")
		self.median_lineedit = QtWidgets.QLineEdit(self.centralwidget)
		self.median_lineedit.setGeometry(QtCore.QRect(130, 250, 221, 21))
		self.median_lineedit.setStyleSheet("background-color: rgb(35, 71, 188); color: rgb(235, 235, 235)")
		self.median_lineedit.setFrame(False)
		self.median_lineedit.setReadOnly(True)
		self.median_lineedit.setObjectName("median_lineedit")
		self.mode_lineedit = QtWidgets.QLineEdit(self.centralwidget)
		self.mode_lineedit.setGeometry(QtCore.QRect(130, 310, 221, 21))
		self.mode_lineedit.setStyleSheet("background-color: rgb(35, 71, 188); color: rgb(235, 235, 235)")
		self.mode_lineedit.setFrame(False)
		self.mode_lineedit.setReadOnly(True)
		self.mode_lineedit.setObjectName("mode_lineedit")
		self.standard_deviation_lineedit = QtWidgets.QLineEdit(self.centralwidget)
		self.standard_deviation_lineedit.setGeometry(QtCore.QRect(270, 430, 221, 21))
		self.standard_deviation_lineedit.setStyleSheet("background-color: rgb(35, 71, 188); color: rgb(235, 235, 235)")
		self.standard_deviation_lineedit.setFrame(False)
		self.standard_deviation_lineedit.setReadOnly(True)
		self.standard_deviation_lineedit.setObjectName("standard_deviation_lineedit")
		self.variance_lineedit = QtWidgets.QLineEdit(self.centralwidget)
		self.variance_lineedit.setGeometry(QtCore.QRect(130, 370, 221, 21))
		self.variance_lineedit.setStyleSheet("background-color: rgb(35, 71, 188); color: rgb(235, 235, 235)")
		self.variance_lineedit.setFrame(False)
		self.variance_lineedit.setReadOnly(True)
		self.variance_lineedit.setObjectName("variance_lineedit")
		self.cv_lineedit = QtWidgets.QLineEdit(self.centralwidget)
		self.cv_lineedit.setGeometry(QtCore.QRect(270, 490, 221, 21))
		self.cv_lineedit.setStyleSheet("background-color: rgb(35, 71, 188); color: rgb(235, 235, 235)")
		self.cv_lineedit.setFrame(False)
		self.cv_lineedit.setReadOnly(True)
		self.cv_lineedit.setObjectName("cv_lineedit")
		self.calculate_button = QtWidgets.QPushButton(self.centralwidget)
		self.calculate_button.setGeometry(QtCore.QRect(390, 130, 120, 23))
		self.input_button = QtWidgets.QPushButton(self.centralwidget)
		self.input_button.setGeometry(QtCore.QRect(360, 129, 24, 24))
		self.input_button.setStyleSheet("background-image : url(Images/help2.png)")
		font = QtGui.QFont()
		font.setFamily("Times New Roman")
		font.setPointSize(14)
		font.setBold(True)
		font.setWeight(75)
		self.calculate_button.setFont(font)
		self.calculate_button.setStyleSheet("QPushButton{color: rgb(255, 96, 16);}\n"
		"QPushButton::pressed{color: rgb(46, 204, 113);}\n"
		"")
		self.calculate_button.setAutoDefault(False)
		self.calculate_button.setObjectName("calculate_button")
		self.line = QtWidgets.QFrame(self.centralwidget)
		self.line.setGeometry(QtCore.QRect(-10, 80, 791, 20))
		self.line.setStyleSheet("color: rgb(46, 204, 113);")
		self.line.setFrameShadow(QtWidgets.QFrame.Plain)
		self.line.setLineWidth(1)
		self.line.setFrameShape(QtWidgets.QFrame.HLine)
		self.line.setObjectName("line")
		self.line_2 = QtWidgets.QFrame(self.centralwidget)
		self.line_2.setGeometry(QtCore.QRect(520, 90, 20, 471))
		self.line_2.setStyleSheet("color: rgb(46, 204, 113);")
		self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
		self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_2.setObjectName("line_2")
		self.graphs_label = QtWidgets.QLabel(self.centralwidget)
		self.graphs_label.setGeometry(QtCore.QRect(610, 130, 91, 31))
		font = QtGui.QFont()
		font.setFamily("Times New Roman")
		font.setPointSize(14)
		font.setBold(False)
		font.setWeight(50)
		self.graphs_label.setFont(font)
		self.graphs_label.setStyleSheet("color:rgb(235, 235, 0);")
		self.graphs_label.setFrameShape(QtWidgets.QFrame.Box)
		self.graphs_label.setLineWidth(2)
		self.graphs_label.setAlignment(QtCore.Qt.AlignCenter)
		self.graphs_label.setObjectName("graphs_label")
		self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
		self.verticalLayoutWidget.setGeometry(QtCore.QRect(570, 200, 181, 261))
		self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
		self.verticalLayout.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout.setObjectName("verticalLayout")
		self.bar_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
		font = QtGui.QFont()
		font.setFamily("Times New Roman")
		font.setPointSize(14)
		font.setBold(True)
		font.setWeight(75)
		self.bar_button.setFont(font)
		self.bar_button.setStyleSheet("QPushButton{color: rgb(255, 96, 16);}\n"
		"QPushButton::pressed{color: rgb(46, 204, 113);}\n"
		"")
		self.bar_button.setAutoDefault(False)
		self.bar_button.setObjectName("bar_button")
		self.verticalLayout.addWidget(self.bar_button)
		self.hist_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
		font = QtGui.QFont()
		font.setFamily("Times New Roman")
		font.setPointSize(14)
		font.setBold(True)
		font.setWeight(75)
		self.hist_button.setFont(font)
		self.hist_button.setStyleSheet("QPushButton{color: rgb(255, 96, 16);}\n"
		"QPushButton::pressed{color: rgb(46, 204, 113);}\n"
		"")
		self.hist_button.setAutoDefault(False)
		self.hist_button.setObjectName("hist_button")
		self.verticalLayout.addWidget(self.hist_button)
		self.scatter_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
		font = QtGui.QFont()
		font.setFamily("Times New Roman")
		font.setPointSize(14)
		font.setBold(True)
		font.setWeight(75)
		self.scatter_button.setFont(font)
		self.scatter_button.setStyleSheet("QPushButton{color: rgb(255, 96, 16);}\n"
		"QPushButton::pressed{color: rgb(46, 204, 113);}\n"
		"")
		self.scatter_button.setAutoDefault(False)
		self.scatter_button.setObjectName("scatter_button")
		self.verticalLayout.addWidget(self.scatter_button)
		self.pie_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
		font = QtGui.QFont()
		font.setFamily("Times New Roman")
		font.setPointSize(14)
		font.setBold(True)
		font.setWeight(75)
		self.pie_button.setFont(font)
		self.pie_button.setStyleSheet("QPushButton{color: rgb(255, 96, 16);}\n"
		"QPushButton::pressed{color: rgb(46, 204, 113);}\n"
		"")
		self.pie_button.setAutoDefault(False)
		self.pie_button.setObjectName("pie_button")
		self.verticalLayout.addWidget(self.pie_button)
		self.exit_button = QtWidgets.QPushButton(self.centralwidget)
		self.exit_button.setGeometry(QtCore.QRect(680, 490, 71, 23))
		MainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 21))
		self.menubar.setObjectName("menubar")
		MainWindow.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)
		self.exit_button.setFont(font)
		self.exit_button.setStyleSheet("QPushButton{color: rgb(255, 96, 16);}\n"
"QPushButton::pressed{color: rgb(46, 204, 113);}\n"
"")
		self.exit_button.setAutoDefault(False)
		self.exit_button.setObjectName("exit_button")
		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

		self.input_button.clicked.connect(self.do_help)
		#############	Calculate & Plots	################
		self.calculate_button.clicked.connect(self.calculate)
		self.calculate_button.setShortcut('Ctrl+E')
		self.bar_button.clicked.connect(self.do_bar)
		self.bar_button.setShortcut('Ctrl+B')
		self.hist_button.clicked.connect(self.do_hist)
		self.hist_button.setShortcut('Ctrl+H')
		self.scatter_button.clicked.connect(self.do_scatter)
		self.scatter_button.setShortcut('Ctrl+S')
		self.pie_button.clicked.connect(self.do_pie)
		self.pie_button.setShortcut('Ctrl+P')

		################### Exit #################
		self.exit_button.setShortcut('Ctrl+Q')
		self.exit_button.clicked.connect(self.exit)


	def calculate(self):
		try:
			text = ''
			file_address = self.input_lineedit.text()
			self.input_lineedit.setStyleSheet("background-color: rgb(35, 71, 188);\n"
			"color: rgb(235, 235, 235);")
			s = ml.statistics()
			s.ReadCSV(file_address)
			self.average_lineedit.setText(str(s.mean()))
			self.median_lineedit.setText(str(s.median()))
			modes = s.mode()
			for key, mode in modes.items():
				text += key + " : " + str(mode) + "\t"
			
			self.mode_lineedit.setText(text)
			
			self.variance_lineedit.setText(str(s.variance()))
			self.standard_deviation_lineedit.setText(str(s.standard_deviation()))
			self.cv_lineedit.setText(str(s.cv()))
		except:
			self.file_address_not_found()

	def do_bar(self):
		try:
			file_address = self.input_lineedit.text()
			s = ml.statistics()
			s.ReadCSV(file_address)
			s.bar_plot()
		except:
			self.file_address_not_found()

	
	def do_pie(self):
		try:
			file_address = self.input_lineedit.text()
			s = ml.statistics()
			s.ReadCSV(file_address)
			s.pie_plot()
		except:
			self.file_address_not_found()


	def do_hist(self):
		try:
			file_address = self.input_lineedit.text()
			s = ml.statistics()
			s.ReadCSV(file_address)
			s.hist_plot()
		except:
			self.file_address_not_found()


	def do_scatter(self):
		try:
			file_address = self.input_lineedit.text()
			s = ml.statistics()
			s.ReadCSV(file_address)
			s.scatter_plot()
		except:
			self.file_address_not_found()

	
	def file_address_not_found(self):
		file_address_message = QtWidgets.QMessageBox()
		file_address_message.question(MainWindow, 'File not found', 'The address you entered is invalid. Please enter a valid file address. for more information click the icon beside the \"Input File\" bar', QtWidgets.QMessageBox.Ok)


	def do_help(self):
		help_message = QtWidgets.QMessageBox()
		help_string = "Valid input files should end with .csv " 
		help_string += "and if you just enter the name the file must be in the same folder with the program. You can enter the full address if you want."
		help_message.question(MainWindow, 'Help', help_string, QtWidgets.QMessageBox.Ok)

	def exit(self):
		exit_box = QtWidgets.QMessageBox()
		is_quit = exit_box.question(MainWindow, 'Quit', 'Are you sure you want to quit?', QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No)
		if is_quit == QtWidgets.QMessageBox.Yes:
			sys.exit()


	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "Fast Insight"))
		self.input_label.setText(_translate("MainWindow", "Input File"))
		self.fast_insight_label.setText(_translate("MainWindow", "Fast Insight"))
		self.input_lineedit.setText(_translate("MainWindow", "Example.csv"))
		self.average_label.setText(_translate("MainWindow", "Average"))
		self.median_label.setText(_translate("MainWindow", "Median"))
		self.mode_label.setText(_translate("MainWindow", "Mode"))
		self.cv_label.setText(_translate("MainWindow", "Coefficient of variation (CV)"))
		self.standard_deviation_label.setText(_translate("MainWindow", "Standard deviation"))
		self.variance_label.setText(_translate("MainWindow", "Variance"))
		self.calculate_button.setText(_translate("MainWindow", "Calculate"))
		self.graphs_label.setText(_translate("MainWindow", "Graphs"))
		self.bar_button.setText(_translate("MainWindow", "Bar"))
		self.hist_button.setText(_translate("MainWindow", "Hist"))
		self.scatter_button.setText(_translate("MainWindow", "Scatter"))
		self.pie_button.setText(_translate("MainWindow", "Pie"))
		self.exit_button.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())
